default-profile: impactlab
profiles:
  impactlab:
    api:
      constructor: {}
      user_config:
        contact: {{contact}}
        name: {{name}}
        team: {{team}}
        institution: {{institution}}
        
    authorities:
      osdc:
        args: [cil-data]
        kwargs:
          calling_format: !!python/object:boto.s3.connection.OrdinaryCallingFormat {}
          host: griffin-objstore.opensciencedatacloud.org
          profile_name: cil
        service: S3FS
    manager:
      class: DynamoDBManager
      kwargs:
        resource_args: {region_name: us-east-1}
        session_args: {profile_name: cil_dynamo}
        table_name: cil-data
